baseURL: 'https://tedw.co.uk'
languageCode: en-us
title: Ted Winder
description: I help teams to deliver digital experiences that drive value and deepen customer relationships by supercharging strategy, storytelling and measurement capabilities.
author: Ted Winder

theme: PaperModTW

summaryLength: 60

enableRobotsTXT: true

googleAnalytics: G-KHX8T0Z10C

permalinks:
  page:
    posts: /posts/:year/:month/:slugorfilename/

params:

  # use an embedded font-family
  # if you import your own fonts, name them here too
  customtextFontFamily: "Onest"
  customheadingFontFamily: "Gloock"

  homeInfoParams:
    Content: Occasional thoughts and reflections.

  dateFormat: "02 January 2006"

  defaultTheme: auto # to switch between dark or light according to browser theme

  buildDrafts: true
      
  ShowReadingTime: true
  enableEmoji: true
  disableSpecial1stPost: true

  disableScrollToTop: true

taxonomies:
  tag: tags

menu:
  main:
    - identifier: home
      name: home
      url: /
      weight: 10
    - identifier: posts
      name: posts
      url: /posts
      weight: 20
    - identifier: linkedin
      name: linkedin
      url: https://www.linkedin.com/in/ted-winder/
      weight: 30

markup:
  goldmark:
    parser:
      attribute:
        block: true