baseURL: 'http://tedw.netlify.app'
languageCode: en-us
title: Ted Winder
theme: PaperModTW

summaryLength: 60

params:

  # use an embedded font-family
  # if you import your own fonts, name them here too
  customtextFontFamily: "Onest"
  customheadingFontFamily: "Gloock"

  homeInfoParams:
    Content: Various musings etc...

  defaultTheme: auto # to switch between dark or light according to browser theme

  buildDrafts: true
      
  ShowReadingTime: true
  enableEmoji: true
  disableSpecial1stPost: true

  disableScrollToTop: true

menu:
  main:
    - identifier: home
      name: home
      url: /
      weight: 10
    - identifier: posts
      name: posts
      url: /posts
      weight: 20
    - identifier: linkedin
      name: linkedin
      url: https://www.linkedin.com/in/ted-winder/
      weight: 30

markup:
  goldmark:
    parser:
      attribute:
        block: true
